# Generated by Django 5.0.1 on 2024-03-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dateof_birth',
            new_name='date_of_birth',
        ),
    ]
